# Generated by Django 5.0.3 on 2024-07-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=50)),
                ('film_description', models.CharField(max_length=200)),
                ('film_tumbnail', models.FileField(upload_to='film_tumbnail')),
                ('film', models.FileField(upload_to='film')),
            ],
        ),
    ]
