# Generated by Django 5.0.3 on 2024-07-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film',
            field=models.FileField(default='null.mp4', upload_to='film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_tumbnail',
            field=models.FileField(default='null.jpg', upload_to='film_tumbnail'),
        ),
    ]
