# Generated by Django 5.0.3 on 2024-07-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_remove_film_film_alter_film_film_tumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_tumbnail',
            field=models.FileField(default='null.mp4', upload_to='film_f'),
        ),
    ]
