# Generated by Django 5.0.3 on 2024-07-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_alter_film_film_tumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film',
            field=models.FileField(default='null.mp4', upload_to='film_f'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_tumbnail',
            field=models.ImageField(default='null.jpg', upload_to='film_tumbnail'),
        ),
    ]
