# Generated by Django 5.0.3 on 2024-07-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_film_film_alter_film_film_tumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='w_count',
            field=models.IntegerField(default=0),
        ),
    ]
