# Generated by Django 5.0.3 on 2024-07-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_film_w_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_genres',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
