# Generated by Django 5.0.3 on 2024-07-19 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_genre_remove_film_film_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genre_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.genre'),
        ),
    ]
