# Generated by Django 5.0.3 on 2024-08-13 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_film_genre_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=20)),
                ('actor_image', models.FileField(default='null.jpg', upload_to='film_cast')),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.film')),
            ],
        ),
    ]
