# Generated by Django 5.0.3 on 2024-08-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcription_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months_in_words', models.CharField(max_length=12)),
                ('months_in_numbers', models.IntegerField()),
                ('plan_price', models.IntegerField()),
            ],
        ),
    ]
