# Generated by Django 5.0.3 on 2024-07-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='u_address',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='u_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='User_email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='user_password',
            field=models.CharField(max_length=8),
        ),
    ]
