# Generated by Django 5.0.3 on 2024-07-31 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_film_genre_id'),
        ('user', '0005_alter_watch_list_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_comment', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.film')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_reg')),
            ],
        ),
    ]
