# Generated by Django 5.0.3 on 2024-07-31 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_comment',
            old_name='User_comment',
            new_name='user_comment',
        ),
    ]
