# Generated by Django 5.0.3 on 2024-08-01 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_film_genre_id'),
        ('user', '0007_rename_user_comment_user_comment_user_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislike_count', models.IntegerField()),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.film')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_reg')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.IntegerField()),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.film')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_reg')),
            ],
        ),
    ]
