# Generated by Django 5.0.3 on 2024-08-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_dislike_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='dislike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
